In [1]:
import pandas as pd

In [5]:
base_features = pd.read_csv('../data/artist_base_features_5_year.csv')
network_features = pd.read_csv('../data/graphs/better_graph/node_features.csv')

In [6]:
network_features.head()

,node,clust_local,triangles,open_wedges,gwesp_score,degree,log_degree,eigencent,kcore,betweenness,...,tri_within_genre,tri_within_label,tri_within_role,tri_cross_genre,tri_cross_label,tri_cross_role,component_size,open_dyads,weak_tie_frac,community_participation
0,5d7df598-bb80-4d73-a6f8-9ed1a4374052,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0
1,5d7e4d03-5c69-4159-b2b7-092dddbcb09f,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0
2,5d7e56b5-91c9-4869-ab9e-072f1760e43d,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0
3,5d7f1460-e2a6-4fc0-86df-6f9a8d129416,1.0,1,0,0.786939,2,1.098612,5.007643e-09,2,0.0,...,1,0,0,0,0,1,4310,13,1.0,0.0
4,5d7f1a01-e08b-44dd-9cab-5a885487250c,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0

In [7]:
base_features.head()

,artist_mbid,artist_name,window_years,debut_date,window_cutoff_date,releases_total,releases_per_year,avg_days_between_releases,release_velocity_releases_per_day,release_velocity_releases_per_year,...,all_roles_str,missing_recordings_flag,missing_genres_flag,missing_labels_flag,missing_releases_flag,recency_index_missing_flag,location_country_known,location_region_city_known,popularity,followers
0,5d7df598-bb80-4d73-a6f8-9ed1a4374052,Earl Hines,5,1902-06-01,1907-06-01,2,0.400055,92.000000,0.010870,3.970109,...,"arranger, composer, instrument, performer, voc...",False,True,False,False,False,True,True,35,33057
1,5d7e4d03-5c69-4159-b2b7-092dddbcb09f,Jean‐Michel Defaye,5,1946-01-01,1951-01-01,1,0.200027,0.000000,0.000000,0.000000,...,"arranger, composer, conductor, instrument, orc...",False,True,False,False,False,True,True,6,173
2,5d7e56b5-91c9-4869-ab9e-072f1760e43d,Mt. Wolf,5,2012-10-06,2017-10-06,5,1.000137,309.000000,0.002468,0.901580,...,NaN,False,True,False,False,False,True,True,43,50965
3,5d7f1460-e2a6-4fc0-86df-6f9a8d129416,DIAMANTA,5,2019-04-10,2024-04-10,2,0.399836,0.000000,0.000000,0.000000,...,writer,False,True,False,False,False,True,True,1,127
4,5d7f1a01-e08b-44dd-9cab-5a885487250c,Fflur Wyn,5,2010-01-01,2015-01-01,4,0.800110,351.666667,0.002804,1.024234,...,vocal,False,True,False,False,False,True,False,4,74

In [10]:
merged = base_features.merge(network_features, how='left', left_on='artist_mbid', right_on='node')

In [16]:
merged = merged[merged['closeness'].notna()]

In [17]:
merged.head()

,artist_mbid,artist_name,window_years,debut_date,window_cutoff_date,releases_total,releases_per_year,avg_days_between_releases,release_velocity_releases_per_day,release_velocity_releases_per_year,...,tri_within_genre,tri_within_label,tri_within_role,tri_cross_genre,tri_cross_label,tri_cross_role,component_size,open_dyads,weak_tie_frac,community_participation
3,5d7f1460-e2a6-4fc0-86df-6f9a8d129416,DIAMANTA,5,2019-04-10,2024-04-10,2,0.399836,0.0,0.000000,0.000000,...,1,0,0,0,0,1,4310,13,1.0,0.0
11,5d875b00-decd-4269-9dc7-074a10ffed26,Danny Connors,5,2018-07-06,2023-07-06,6,1.200164,231.0,0.002930,1.070141,...,0,0,0,0,0,0,2,0,1.0,0.0
16,5d89b884-37b6-43bd-91a4-997257c7b36a,Finalfix,5,2022-02-16,2027-02-16,3,0.792299,225.0,0.004210,1.537641,...,0,0,0,0,0,0,2,0,1.0,0.0
27,5d91a884-e3f2-40f8-a81a-d015448ef4d0,김원필,5,2020-05-11,2025-05-11,6,1.200164,75.6,0.009665,3.530308,...,0,0,0,0,0,0,2,0,1.0,0.0
29,5d93170f-9b5b-4718-8459-3fdce013b637,Groove 2070,5,2024-09-12,2029-09-12,2,1.645270,35.0,0.028571,10.435714,...,0,0,0,0,0,0,4310,6,1.0,0.0

In [18]:
merged.shape

(14183, 74)

In [19]:
merged.to_csv('../data/all_features_5_year.csv')

In [23]:
filtered_artist_mbids = set(merged['artist_mbid'])

In [22]:
base_features = base_features[base_features['artist_mbid'].isin(filtered_artist_mbids)]

In [25]:
base_features.to_csv('../data/artist_base_features_5_year.csv')