In [27]:
import pandas as pd

In [28]:
base_features = pd.read_csv('../data/artist_base_features_5_year.csv')
network_features = pd.read_csv('../data/graphs/better_graph/node_features.csv')

In [29]:
network_features.head()

,node,clust_local,triangles,open_wedges,gwesp_score,degree,log_degree,eigencent,kcore,betweenness,...,tri_within_genre,tri_within_label,tri_within_role,tri_cross_genre,tri_cross_label,tri_cross_role,component_size,open_dyads,weak_tie_frac,community_participation
0,5d7df598-bb80-4d73-a6f8-9ed1a4374052,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0
1,5d7e4d03-5c69-4159-b2b7-092dddbcb09f,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0
2,5d7e56b5-91c9-4869-ab9e-072f1760e43d,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0
3,5d7f1460-e2a6-4fc0-86df-6f9a8d129416,1.0,1,0,0.786939,2,1.098612,5.007643e-09,2,0.0,...,1,0,0,0,0,1,4310,13,1.0,0.0
4,5d7f1a01-e08b-44dd-9cab-5a885487250c,0.0,0,0,0.000000,0,0.000000,0.000000e+00,0,0.0,...,0,0,0,0,0,0,1,0,0.0,0.0

In [30]:
base_features.head()

,Unnamed: 0,artist_mbid,artist_name,window_years,debut_date,window_cutoff_date,releases_total,releases_per_year,avg_days_between_releases,release_velocity_releases_per_day,...,all_roles_str,missing_recordings_flag,missing_genres_flag,missing_labels_flag,missing_releases_flag,recency_index_missing_flag,location_country_known,location_region_city_known,popularity,followers
0,3,5d7f1460-e2a6-4fc0-86df-6f9a8d129416,DIAMANTA,5,2019-04-10,2024-04-10,2,0.399836,0.0,0.000000,...,writer,False,True,False,False,False,True,True,1,127
1,11,5d875b00-decd-4269-9dc7-074a10ffed26,Danny Connors,5,2018-07-06,2023-07-06,6,1.200164,231.0,0.002930,...,"instrument, writer",False,True,False,False,False,True,False,10,248
2,16,5d89b884-37b6-43bd-91a4-997257c7b36a,Finalfix,5,2022-02-16,2027-02-16,3,0.792299,225.0,0.004210,...,"composer, producer, remixer, writer",False,True,False,False,False,False,False,21,4392
3,27,5d91a884-e3f2-40f8-a81a-d015448ef4d0,김원필,5,2020-05-11,2025-05-11,6,1.200164,75.6,0.009665,...,"composer, lyricist, vocal",False,True,False,False,False,True,True,43,126495
4,29,5d93170f-9b5b-4718-8459-3fdce013b637,Groove 2070,5,2024-09-12,2029-09-12,2,1.645270,35.0,0.028571,...,"producer, writer",False,True,False,False,False,True,False,19,438

In [31]:
merged = base_features.merge(network_features, how='left', left_on='artist_mbid', right_on='node')

In [32]:
merged = merged[merged['closeness'].notna()]

In [33]:
merged.head()

,Unnamed: 0,artist_mbid,artist_name,window_years,debut_date,window_cutoff_date,releases_total,releases_per_year,avg_days_between_releases,release_velocity_releases_per_day,...,tri_within_genre,tri_within_label,tri_within_role,tri_cross_genre,tri_cross_label,tri_cross_role,component_size,open_dyads,weak_tie_frac,community_participation
0,3,5d7f1460-e2a6-4fc0-86df-6f9a8d129416,DIAMANTA,5,2019-04-10,2024-04-10,2,0.399836,0.0,0.000000,...,1,0,0,0,0,1,4310,13,1.0,0.0
1,11,5d875b00-decd-4269-9dc7-074a10ffed26,Danny Connors,5,2018-07-06,2023-07-06,6,1.200164,231.0,0.002930,...,0,0,0,0,0,0,2,0,1.0,0.0
2,16,5d89b884-37b6-43bd-91a4-997257c7b36a,Finalfix,5,2022-02-16,2027-02-16,3,0.792299,225.0,0.004210,...,0,0,0,0,0,0,2,0,1.0,0.0
3,27,5d91a884-e3f2-40f8-a81a-d015448ef4d0,김원필,5,2020-05-11,2025-05-11,6,1.200164,75.6,0.009665,...,0,0,0,0,0,0,2,0,1.0,0.0
4,29,5d93170f-9b5b-4718-8459-3fdce013b637,Groove 2070,5,2024-09-12,2029-09-12,2,1.645270,35.0,0.028571,...,0,0,0,0,0,0,4310,6,1.0,0.0

In [34]:
merged.shape

(14183, 75)

In [35]:
merged.to_csv('../data/all_features_5_year.csv')

In [36]:
filtered_artist_mbids = set(merged['artist_mbid'])

In [37]:
base_features = base_features[base_features['artist_mbid'].isin(filtered_artist_mbids)]

In [38]:
base_features.to_csv('../data/artist_base_features_5_year.csv')

In [42]:
merged.columns

Index(['Unnamed: 0', 'artist_mbid', 'artist_name', 'window_years',
       'debut_date', 'window_cutoff_date', 'releases_total',
       'releases_per_year', 'avg_days_between_releases',
       'release_velocity_releases_per_day',
       'release_velocity_releases_per_year', 'gap_median_days', 'gap_std_days',
       'max_dry_spell_days', 'front_loading_index', 'tracks_total',
       'collab_track_rate', 'unique_collaborator_count',
       'label_diversity_count', 'label_churn', 'label_hhi', 'primary_label',
       'all_labels_str', 'duration_ms_mean', 'duration_ms_median',
       'duration_ms_min', 'duration_ms_max', 'remix_rate', 'acoustic_rate',
       'genre_count', 'genre_entropy', 'primary_genre', 'all_genres_str',
       'artist_country', 'artist_region_city', 'years_active', 'debut_year',
       'debut_decade', 'recency_index', 'primary_role', 'all_roles_str',
       'missing_recordings_flag', 'missing_genres_flag', 'missing_labels_flag',
       'missing_releases_flag', 'recency_index_missing_flag',
       'location_country_known', 'location_region_city_known', 'popularity',
       'followers', 'node', 'clust_local', 'triangles', 'open_wedges',
       'gwesp_score', 'degree', 'log_degree', 'eigencent', 'kcore',
       'betweenness', 'closeness', 'dist_to_hub_min', 'same_genre_share',
       'same_label_share', 'same_role_share', 'tri_within_genre',
       'tri_within_label', 'tri_within_role', 'tri_cross_genre',
       'tri_cross_label', 'tri_cross_role', 'component_size', 'open_dyads',
       'weak_tie_frac', 'community_participation'],
      dtype='object')

In [43]:
merged['Unnamed: 0']

0             3
1            11
2            16
3            27
4            29
          ...
14178    112474
14179    112483
14180    112488
14181    112497
14182    112501
Name: Unnamed: 0, Length: 14183, dtype: int64